name: 'Linting'
on:
  push:

jobs:
  Linting:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install
      - name: Run linter
        run: npm run lint
